//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWTNFCompleto.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefa.pr.gov.br/nfe/NFeInutilizacao4")]
        public string IWTNFCompleto_NfeInutilizacao_NfeInutilizacao3 {
            get {
                return ((string)(this["IWTNFCompleto_NfeInutilizacao_NfeInutilizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta4")]
        public string IWTNFCompleto_NfeConsulta_NfeConsulta3 {
            get {
                return ((string)(this["IWTNFCompleto_NfeConsulta_NfeConsulta3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefa.pr.gov.br/nfe/NFeStatusServico4")]
        public string IWTNFCompleto_NfeStatusServico_NfeStatusServico3 {
            get {
                return ((string)(this["IWTNFCompleto_NfeStatusServico_NfeStatusServico3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefa.pr.gov.br/nfe/CadConsultaCadastro4")]
        public string IWTNFCompleto_CadConsultaCadastro_CadConsultaCadastro2 {
            get {
                return ((string)(this["IWTNFCompleto_CadConsultaCadastro_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefa.pr.gov.br/nfe/NFeRecepcaoEvento4")]
        public string IWTNFCompleto_RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["IWTNFCompleto_RecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefa.pr.gov.br/nfe/NFeAutorizacao4")]
        public string IWTNFCompleto_NfeAutorizacao_NfeAutorizacao3 {
            get {
                return ((string)(this["IWTNFCompleto_NfeAutorizacao_NfeAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefa.pr.gov.br/nfe/NFeRetAutorizacao4")]
        public string IWTNFCompleto_NfeRetAutorizacao_NfeRetAutorizacao3 {
            get {
                return ((string)(this["IWTNFCompleto_NfeRetAutorizacao_NfeRetAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe-hml.sefaz.rs.gov.br/ws/MDFeStatusServico/MDFeStatusServico.asmx")]
        public string IWTNFCompleto_MDFeStatusServico_MDFeStatusServico {
            get {
                return ((string)(this["IWTNFCompleto_MDFeStatusServico_MDFeStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe-hml.sefaz.rs.gov.br/ws/MDFerecepcao/MDFeRecepcao.asmx")]
        public string IWTNFCompleto_MDFeRecepcao_MDFeRecepcao {
            get {
                return ((string)(this["IWTNFCompleto_MDFeRecepcao_MDFeRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe-hml.sefaz.rs.gov.br/ws/MDFeRetRecepcao/MDFeRetRecepcao.asmx")]
        public string IWTNFCompleto_MDFeRetRecepcao_MDFeRetRecepcao {
            get {
                return ((string)(this["IWTNFCompleto_MDFeRetRecepcao_MDFeRetRecepcao"]));
            }
        }
    }
}
