//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIpiIPINT", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TIpiIPINT
    {
        
        /// <summary>
        /// <para>Código da Situação Tributária do IPI:
        ///01-Entrada tributada com alíquota zero
        ///02-Entrada isenta
        ///03-Entrada não-tributada
        ///04-Entrada imune
        ///05-Entrada com suspensão
        ///51-Saída tributada com alíquota zero
        ///52-Saída isenta
        ///53-Saída não-tributada
        ///54-Saída imune
        ///55-Saída com suspensão</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Código da Situação Tributária do IPI: 01-Entrada tributada com alíquota zero 02-Entrada isenta 03-Entrada não-tributada 04-Entrada imune 05-Entrada com suspensão 51-Saída tributada com alíquota zero 52-Saída isenta 53-Saída não-tributada 54-Saída imune 55-Saída com suspensão")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CST")]
        public TIpiIPINTCST CST { get; set; }
    }
}
