//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeInfAdic", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeInfAdic
    {
        
        /// <summary>
        /// <para>Informações adicionais de interesse do Fisco (v2.0)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informações adicionais de interesse do Fisco (v2.0)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("infAdFisco")]
        public string infAdFisco { get; set; }
        
        /// <summary>
        /// <para>Informações complementares de interesse do Contribuinte</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 5000.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informações complementares de interesse do Contribuinte")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(5000)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("infCpl")]
        public string infCpl { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TNFeInfNFeInfAdicObsCont> _obsCont;
        
        /// <summary>
        /// <para>Campo de uso livre do contribuinte
        ///informar o nome do campo no atributo xCampo
        ///e o conteúdo do campo no xTexto</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Campo de uso livre do contribuinte informar o nome do campo no atributo xCampo e " +
            "o conteúdo do campo no xTexto")]
        [System.Xml.Serialization.XmlElementAttribute("obsCont")]
        public System.Collections.ObjectModel.Collection<TNFeInfNFeInfAdicObsCont> obsCont
        {
            get
            {
                return _obsCont;
            }
            private set
            {
                _obsCont = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the obsCont collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obsContSpecified
        {
            get
            {
                return (this.obsCont.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TNFeInfNFeInfAdic" /> class.</para>
        /// </summary>
        public TNFeInfNFeInfAdic()
        {
            this._obsCont = new System.Collections.ObjectModel.Collection<TNFeInfNFeInfAdicObsCont>();
            this._obsFisco = new System.Collections.ObjectModel.Collection<TNFeInfNFeInfAdicObsFisco>();
            this._procRef = new System.Collections.ObjectModel.Collection<TNFeInfNFeInfAdicProcRef>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TNFeInfNFeInfAdicObsFisco> _obsFisco;
        
        /// <summary>
        /// <para>Campo de uso exclusivo do Fisco
        ///informar o nome do campo no atributo xCampo
        ///e o conteúdo do campo no xTexto</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Campo de uso exclusivo do Fisco informar o nome do campo no atributo xCampo e o c" +
            "onteúdo do campo no xTexto")]
        [System.Xml.Serialization.XmlElementAttribute("obsFisco")]
        public System.Collections.ObjectModel.Collection<TNFeInfNFeInfAdicObsFisco> obsFisco
        {
            get
            {
                return _obsFisco;
            }
            private set
            {
                _obsFisco = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the obsFisco collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obsFiscoSpecified
        {
            get
            {
                return (this.obsFisco.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TNFeInfNFeInfAdicProcRef> _procRef;
        
        /// <summary>
        /// <para>Grupo de informações do  processo referenciado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do processo referenciado")]
        [System.Xml.Serialization.XmlElementAttribute("procRef")]
        public System.Collections.ObjectModel.Collection<TNFeInfNFeInfAdicProcRef> procRef
        {
            get
            {
                return _procRef;
            }
            private set
            {
                _procRef = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the procRef collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool procRefSpecified
        {
            get
            {
                return (this.procRef.Count != 0);
            }
        }
    }
}
