//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeIdeNFrefRefECF", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeIdeNFrefRefECF
    {
        
        /// <summary>
        /// <para>Código do modelo do Documento Fiscal 
        ///Preencher com "2B", quando se tratar de Cupom Fiscal emitido por máquina registradora (não ECF), com "2C", quando se tratar de Cupom Fiscal PDV, ou "2D", quando se tratar de Cupom Fiscal (emitido por ECF)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código do modelo do Documento Fiscal Preencher com \"2B\", quando se tratar de Cupo" +
            "m Fiscal emitido por máquina registradora (não ECF), com \"2C\", quando se tratar " +
            "de Cupom Fiscal PDV, ou \"2D\", quando se tratar de Cupom Fiscal (emitido por ECF)" +
            "")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("mod")]
        public TNFeInfNFeIdeNFrefRefECFMod mod { get; set; }
        
        /// <summary>
        /// <para>Informar o número de ordem seqüencial do ECF que emitiu o Cupom Fiscal vinculado à NF-e</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,3}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informar o número de ordem seqüencial do ECF que emitiu o Cupom Fiscal vinculado " +
            "à NF-e")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,3}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nECF")]
        public string NECF { get; set; }
        
        /// <summary>
        /// <para>Informar o Número do Contador de Ordem de Operação - COO vinculado à NF-e</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,6}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informar o Número do Contador de Ordem de Operação - COO vinculado à NF-e")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,6}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nCOO")]
        public string NCOO { get; set; }
    }
}
