//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeDetImpostoISSQN", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeDetImpostoISSQN
    {
        
        /// <summary>
        /// <para>Valor da BC do ISSQN</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor da BC do ISSQN")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vBC")]
        public string vBC { get; set; }
        
        /// <summary>
        /// <para>Alíquota do ISSQN</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota do ISSQN")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vAliq")]
        public string vAliq { get; set; }
        
        /// <summary>
        /// <para>Valor da do ISSQN</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor da do ISSQN")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vISSQN")]
        public string vISSQN { get; set; }
        
        /// <summary>
        /// <para>Informar o município de ocorrência do fato gerador do ISSQN. Utilizar a Tabela do IBGE (Anexo VII - Tabela de UF, Município e País). “Atenção, não vincular com os campos B12, C10 ou E10” v2.0</para>
        /// <para>Tipo Código do Município da tabela do IBGE</para>
        /// <para xml:lang="en">Pattern: [0-9]{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informar o município de ocorrência do fato gerador do ISSQN. Utilizar a Tabela do" +
            " IBGE (Anexo VII - Tabela de UF, Município e País). “Atenção, não vincular com o" +
            "s campos B12, C10 ou E10” v2.0")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cMunFG")]
        public string cMunFG { get; set; }
        
        /// <summary>
        /// <para>Informar o Item da lista de serviços da LC 116/03 em que se classifica o serviço.</para>
        /// <para>Tipo Código da Lista de Serviços LC 116/2003</para>
        /// <para xml:lang="en">Pattern: [0-9]{2}.[0-9]{2}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informar o Item da lista de serviços da LC 116/03 em que se classifica o serviço." +
            "")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{2}.[0-9]{2}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cListServ")]
        public string cListServ { get; set; }
        
        /// <summary>
        /// <para>Valor dedução para redução da base de cálculo</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais, utilizado em tags opcionais</para>
        /// <para xml:lang="en">Pattern: 0\.[0-9]{1}[1-9]{1}|0\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor dedução para redução da base de cálculo")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0\\.[0-9]{1}[1-9]{1}|0\\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vDeducao")]
        public string VDeducao { get; set; }
        
        /// <summary>
        /// <para>Valor outras retenções</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais, utilizado em tags opcionais</para>
        /// <para xml:lang="en">Pattern: 0\.[0-9]{1}[1-9]{1}|0\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor outras retenções")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0\\.[0-9]{1}[1-9]{1}|0\\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vOutro")]
        public string vOutro { get; set; }
        
        /// <summary>
        /// <para>Valor desconto incondicionado</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais, utilizado em tags opcionais</para>
        /// <para xml:lang="en">Pattern: 0\.[0-9]{1}[1-9]{1}|0\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor desconto incondicionado")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0\\.[0-9]{1}[1-9]{1}|0\\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vDescIncond")]
        public string VDescIncond { get; set; }
        
        /// <summary>
        /// <para>Valor desconto condicionado</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais, utilizado em tags opcionais</para>
        /// <para xml:lang="en">Pattern: 0\.[0-9]{1}[1-9]{1}|0\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor desconto condicionado")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0\\.[0-9]{1}[1-9]{1}|0\\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vDescCond")]
        public string VDescCond { get; set; }
        
        /// <summary>
        /// <para>Valor Retenção ISS</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais, utilizado em tags opcionais</para>
        /// <para xml:lang="en">Pattern: 0\.[0-9]{1}[1-9]{1}|0\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor Retenção ISS")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0\\.[0-9]{1}[1-9]{1}|0\\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vISSRet")]
        public string VISSRet { get; set; }
        
        /// <summary>
        /// <para>Exibilidade do ISS:1-Exigível;2-Não incidente;3-Isenção;4-Exportação;5-Imunidade;6-Exig.Susp. Judicial;7-Exig.Susp. ADM</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Exibilidade do ISS:1-Exigível;2-Não incidente;3-Isenção;4-Exportação;5-Imunidade;" +
            "6-Exig.Susp. Judicial;7-Exig.Susp. ADM")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("indISS")]
        public TNFeInfNFeDetImpostoISSQNIndISS IndISS { get; set; }
        
        /// <summary>
        /// <para>Código do serviço prestado dentro do município</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código do serviço prestado dentro do município")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("cServico")]
        public string CServico { get; set; }
        
        /// <summary>
        /// <para>Código do Município de Incidência do Imposto</para>
        /// <para>Tipo Código do Município da tabela do IBGE</para>
        /// <para xml:lang="en">Pattern: [0-9]{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código do Município de Incidência do Imposto")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        [System.Xml.Serialization.XmlElementAttribute("cMun")]
        public string cMun { get; set; }
        
        /// <summary>
        /// <para>Código de Pais</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,4}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código de Pais")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,4}")]
        [System.Xml.Serialization.XmlElementAttribute("cPais")]
        public string cPais { get; set; }
        
        /// <summary>
        /// <para>Número do Processo administrativo ou judicial de suspenção do processo</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do Processo administrativo ou judicial de suspenção do processo")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("nProcesso")]
        public string nProcesso { get; set; }
        
        /// <summary>
        /// <para>Indicador de Incentivo Fiscal. 1=Sim; 2=Não</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Indicador de Incentivo Fiscal. 1=Sim; 2=Não")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("indIncentivo")]
        public TNFeInfNFeDetImpostoISSQNIndIncentivo indIncentivo { get; set; }
    }
}
