//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeDetImpostoPISPISNTCST", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    public enum TNFeInfNFeDetImpostoPISPISNTCST
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
        
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
        
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,
    }
}
