//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    /// <summary>
    /// <para>Tipo Pedido de Consulta do Recido do Lote de Notas Fiscais Eletrônicas</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo Pedido de Consulta do Recido do Lote de Notas Fiscais Eletrônicas")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TConsReciNFe", Namespace="http://www.portalfiscal.inf.br/nfe")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TConsReciNFe
    {
        
        /// <summary>
        /// <para>Identificação do Ambiente:
        ///1 - Produção
        ///2 - Homologação</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identificação do Ambiente: 1 - Produção 2 - Homologação")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpAmb")]
        public IWTNFCompleto.BibliotecaDatasets.v4_0.TAmb tpAmb { get; set; }
        
        /// <summary>
        /// <para>Número do Recibo</para>
        /// <para>Tipo Número do Recibo do envio de lote de NF-e</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [0-9]{15}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do Recibo")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{15}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nRec")]
        public string nRec { get; set; }
        
        /// <summary>
        /// <para>Tipo Versão da NF-e - 4.00</para>
        /// <para xml:lang="en">Pattern: 4\.00.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("4\\.00")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("versao")]
        public string versao { get; set; }
    }
}
