//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retInutNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TInutNFeInfInut", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TInutNFeInfInut
    {
        
        /// <summary>
        /// <para>Identificação do Ambiente:
        ///1 - Produção
        ///2 - Homologação</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identificação do Ambiente: 1 - Produção 2 - Homologação")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpAmb")]
        public IWTNFCompleto.BibliotecaDatasets.v4_0.TAmb tpAmb { get; set; }
        
        /// <summary>
        /// <para>Serviço Solicitado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Serviço Solicitado")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("xServ")]
        public TInutNFeInfInutXServ xServ { get; set; }
        
        /// <summary>
        /// <para>Código da UF do emitente</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código da UF do emitente")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cUF")]
        public IWTNFCompleto.BibliotecaDatasets.v4_0.TCodUfIBGE cUF { get; set; }
        
        /// <summary>
        /// <para>Ano de inutilização da numeração</para>
        /// <para>Tipo ano</para>
        /// <para xml:lang="en">Pattern: [0-9]{2}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ano de inutilização da numeração")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{2}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ano")]
        public string ano { get; set; }
        
        /// <summary>
        /// <para>CNPJ do emitente</para>
        /// <para>Tipo Número do CNPJ</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CNPJ do emitente")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CNPJ")]
        public string CNPJ { get; set; }
        
        /// <summary>
        /// <para>Modelo da NF-e (55, 65 etc.)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Modelo da NF-e (55, 65 etc.)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("mod")]
        public IWTNFCompleto.BibliotecaDatasets.v4_0.TMod mod { get; set; }
        
        /// <summary>
        /// <para>Série da NF-e</para>
        /// <para>Tipo Série do Documento Fiscal</para>
        /// <para xml:lang="en">Pattern: 0|[1-9]{1}[0-9]{0,2}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Série da NF-e")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|[1-9]{1}[0-9]{0,2}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("serie")]
        public string serie { get; set; }
        
        /// <summary>
        /// <para>Número da NF-e inicial</para>
        /// <para>Tipo Número do Documento Fiscal</para>
        /// <para xml:lang="en">Pattern: [1-9]{1}[0-9]{0,8}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número da NF-e inicial")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]{1}[0-9]{0,8}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nNFIni")]
        public string nNFIni { get; set; }
        
        /// <summary>
        /// <para>Número da NF-e final</para>
        /// <para>Tipo Número do Documento Fiscal</para>
        /// <para xml:lang="en">Pattern: [1-9]{1}[0-9]{0,8}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número da NF-e final")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]{1}[0-9]{0,8}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nNFFin")]
        public string nNFFin { get; set; }
        
        /// <summary>
        /// <para>Justificativa do pedido de inutilização</para>
        /// <para>Tipo Justificativa</para>
        /// <para xml:lang="en">Minimum length: 15.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Justificativa do pedido de inutilização")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xJust")]
        public string xJust { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: ID[0-9]{41}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("ID[0-9]{41}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
    }
}
