//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    /// <summary>
    /// <para>Tipo Dados do Local de Retirada ou Entrega // 24/10/08 - tamanho mínimo // v2.0</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo Dados do Local de Retirada ou Entrega // 24/10/08 - tamanho mínimo // v2.0")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TLocal", Namespace="http://www.portalfiscal.inf.br/nfe")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TLocal
    {
        
        /// <summary>
        /// <para>CNPJ</para>
        /// <para>Tipo Número do CNPJ Opcional</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{0}|[0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CNPJ")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{0}|[0-9]{14}")]
        [System.Xml.Serialization.XmlElementAttribute("CNPJ", Order=0)]
        public string CNPJ { get; set; }
        
        /// <summary>
        /// <para>CPF (v2.0)</para>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CPF (v2.0)")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.Xml.Serialization.XmlElementAttribute("CPF", Order=1)]
        public string CPF { get; set; }
        
        /// <summary>
        /// <para>Razão Social ou Nome do Expedidor/Recebedor</para>
        /// <para xml:lang="en">Minimum length: 2.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Razão Social ou Nome do Expedidor/Recebedor")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("xNome", Order=2)]
        public string xNome { get; set; }
        
        /// <summary>
        /// <para>Logradouro</para>
        /// <para xml:lang="en">Minimum length: 2.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Logradouro")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xLgr", Order=3)]
        public string xLgr { get; set; }
        
        /// <summary>
        /// <para>Número</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("nro", Order=4)]
        public string nro { get; set; }
        
        /// <summary>
        /// <para>Complemento</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Complemento")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("xCpl", Order=5)]
        public string xCpl { get; set; }
        
        /// <summary>
        /// <para>Bairro</para>
        /// <para xml:lang="en">Minimum length: 2.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Bairro")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xBairro", Order=6)]
        public string xBairro { get; set; }
        
        /// <summary>
        /// <para>Código do município (utilizar a tabela do IBGE)</para>
        /// <para>Tipo Código do Município da tabela do IBGE</para>
        /// <para xml:lang="en">Pattern: [0-9]{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código do município (utilizar a tabela do IBGE)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cMun", Order=7)]
        public string cMun { get; set; }
        
        /// <summary>
        /// <para>Nome do município</para>
        /// <para xml:lang="en">Minimum length: 2.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nome do município")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xMun", Order=8)]
        public string xMun { get; set; }
        
        /// <summary>
        /// <para>Sigla da UF</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Sigla da UF")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("UF", Order=9)]
        public IWTNFCompleto.BibliotecaDatasets.v4_0.TUf UF { get; set; }
        
        /// <summary>
        /// <para>CEP</para>
        /// <para xml:lang="en">Pattern: [0-9]{8}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CEP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{8}")]
        [System.Xml.Serialization.XmlElementAttribute("CEP", Order=10)]
        public string CEP { get; set; }
        
        /// <summary>
        /// <para>Código de Pais</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,4}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código de Pais")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,4}")]
        [System.Xml.Serialization.XmlElementAttribute("cPais", Order=11)]
        public string cPais { get; set; }
        
        /// <summary>
        /// <para>Nome do país</para>
        /// <para xml:lang="en">Minimum length: 2.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nome do país")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("xPais", Order=12)]
        public string xPais { get; set; }
        
        /// <summary>
        /// <para>Telefone, preencher com Código DDD + número do telefone , nas operações com exterior é permtido informar o código do país + código da localidade + número do telefone</para>
        /// <para xml:lang="en">Pattern: [0-9]{6,14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Telefone, preencher com Código DDD + número do telefone , nas operações com exter" +
            "ior é permtido informar o código do país + código da localidade + número do tele" +
            "fone")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{6,14}")]
        [System.Xml.Serialization.XmlElementAttribute("fone", Order=13)]
        public string fone { get; set; }
        
        /// <summary>
        /// <para>Informar o e-mail do expedidor/Recebedor. O campo pode ser utilizado para informar o e-mail de recepção da NF-e indicada pelo expedidor</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informar o e-mail do expedidor/Recebedor. O campo pode ser utilizado para informa" +
            "r o e-mail de recepção da NF-e indicada pelo expedidor")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("email", Order=14)]
        public string email { get; set; }
        
        /// <summary>
        /// <para>Inscrição Estadual (v2.0)</para>
        /// <para>Tipo Inscrição Estadual do Emitente // alterado EM 24/10/08 para aceitar ISENTO</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{2,14}|ISENTO.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Inscrição Estadual (v2.0)")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{2,14}|ISENTO")]
        [System.Xml.Serialization.XmlElementAttribute("IE", Order=15)]
        public string IE { get; set; }
    }
}
