//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order "C:\Projetos.git\marco_teste\Novos XSD\PL_010b_NT2025_002_v1.30\nfe_v4.00.xsd"
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TMonofasiaGMonoRet", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TMonofasiaGMonoRet
    {
        
        /// <summary>
        /// <para>Quantidade tributada retida anteriormente</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 11 de corpo e 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{4}|[1-9]{1}[0-9]{0,10}(\.[0-9]{4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Quantidade tributada retida anteriormente")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{4}|[1-9]{1}[0-9]{0,10}(\\.[0-9]{4})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("qBCMonoRet", Order=0)]
        public string QBCMonoRet { get; set; }
        
        /// <summary>
        /// <para>Alíquota ad rem do IBS retido anteriormente</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota ad rem do IBS retido anteriormente")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("adRemIBSRet", Order=1)]
        public string AdRemIBSRet { get; set; }
        
        /// <summary>
        /// <para>Valor do IBS retido anteriormente</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor do IBS retido anteriormente")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vIBSMonoRet", Order=2)]
        public string VIBSMonoRet { get; set; }
        
        /// <summary>
        /// <para>Alíquota ad rem da CBS retida anteriormente</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota ad rem da CBS retida anteriormente")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("adRemCBSRet", Order=3)]
        public string AdRemCBSRet { get; set; }
        
        /// <summary>
        /// <para>Valor da CBS retida anteriormente</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor da CBS retida anteriormente")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vCBSMonoRet", Order=4)]
        public string VCBSMonoRet { get; set; }
    }
}
