//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order "C:\Projetos.git\marco_teste\Novos XSD\PL_010b_NT2025_002_v1.30\nfe_v4.00.xsd"
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeDetImpostoICMSICMSSN900", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeDetImpostoICMSICMSSN900
    {
        
        /// <summary>
        /// <para>origem da mercadoria: 0 - Nacional 
        ///1 - Estrangeira - Importação direta 
        ///2 - Estrangeira - Adquirida no mercado interno</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("origem da mercadoria: 0 - Nacional 1 - Estrangeira - Importação direta 2 - Estran" +
            "geira - Adquirida no mercado interno")]
        [System.Xml.Serialization.XmlElementAttribute("orig", Order=0)]
        public Torig orig { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the orig property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool origSpecified { get; set; }
        
        /// <summary>
        /// <para>Tributação pelo ICMS 900 - Outros(v2.0)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação pelo ICMS 900 - Outros(v2.0)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CSOSN", Order=1)]
        public TNFeInfNFeDetImpostoICMSICMSSN900CSOSN CSOSN { get; set; }
        
        /// <summary>
        /// <para>Modalidade de determinação da BC do ICMS: 
        ///0 - Margem Valor Agregado (%);
        ///1 - Pauta (valor);
        ///2 - Preço Tabelado Máximo (valor);
        ///3 - Valor da Operação.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Modalidade de determinação da BC do ICMS: 0 - Margem Valor Agregado (%); 1 - Paut" +
            "a (valor); 2 - Preço Tabelado Máximo (valor); 3 - Valor da Operação.")]
        [System.Xml.Serialization.XmlElementAttribute("modBC", Order=2)]
        public TNFeInfNFeDetImpostoICMSICMSSN900ModBC modBC { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the modBC property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modBCSpecified { get; set; }
        
        /// <summary>
        /// <para>Valor da BC do ICMS</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor da BC do ICMS")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vBC", Order=3)]
        public string vBC { get; set; }
        
        /// <summary>
        /// <para>Percentual de redução da BC</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros e 2 até 4 decimais. Utilizados em TAGs opcionais, não aceita valor zero.</para>
        /// <para xml:lang="en">Pattern: 0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Percentual de redução da BC")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.Xml.Serialization.XmlElementAttribute("pRedBC", Order=4)]
        public string pRedBC { get; set; }
        
        /// <summary>
        /// <para>Alíquota do ICMS</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota do ICMS")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.Xml.Serialization.XmlElementAttribute("pICMS", Order=5)]
        public string pICMS { get; set; }
        
        /// <summary>
        /// <para>Valor do ICMS</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor do ICMS")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vICMS", Order=6)]
        public string vICMS { get; set; }
        
        /// <summary>
        /// <para>Modalidade de determinação da BC do ICMS ST:
        ///0 – Preço tabelado ou máximo  sugerido;
        ///1 - Lista Negativa (valor);
        ///2 - Lista Positiva (valor);
        ///3 - Lista Neutra (valor);
        ///4 - Margem Valor Agregado (%);
        ///5 - Pauta (valor).
        ///6 - Valor da Operação</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Modalidade de determinação da BC do ICMS ST: 0 – Preço tabelado ou máximo sugerid" +
            "o; 1 - Lista Negativa (valor); 2 - Lista Positiva (valor); 3 - Lista Neutra (val" +
            "or); 4 - Margem Valor Agregado (%); 5 - Pauta (valor). 6 - Valor da Operação")]
        [System.Xml.Serialization.XmlElementAttribute("modBCST", Order=7)]
        public TNFeInfNFeDetImpostoICMSICMSSN900ModBCST modBCST { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the modBCST property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modBCSTSpecified { get; set; }
        
        /// <summary>
        /// <para>Percentual da Margem de Valor Adicionado ICMS ST</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros e 2 até 4 decimais. Utilizados em TAGs opcionais, não aceita valor zero.</para>
        /// <para xml:lang="en">Pattern: 0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Percentual da Margem de Valor Adicionado ICMS ST")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.Xml.Serialization.XmlElementAttribute("pMVAST", Order=8)]
        public string pMVAST { get; set; }
        
        /// <summary>
        /// <para>Percentual de redução da BC ICMS ST</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros e 2 até 4 decimais. Utilizados em TAGs opcionais, não aceita valor zero.</para>
        /// <para xml:lang="en">Pattern: 0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Percentual de redução da BC ICMS ST")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.Xml.Serialization.XmlElementAttribute("pRedBCST", Order=9)]
        public string pRedBCST { get; set; }
        
        /// <summary>
        /// <para>Valor da BC do ICMS ST</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor da BC do ICMS ST")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vBCST", Order=10)]
        public string vBCST { get; set; }
        
        /// <summary>
        /// <para>Alíquota do ICMS ST</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota do ICMS ST")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.Xml.Serialization.XmlElementAttribute("pICMSST", Order=11)]
        public string pICMSST { get; set; }
        
        /// <summary>
        /// <para>Valor do ICMS ST</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor do ICMS ST")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vICMSST", Order=12)]
        public string vICMSST { get; set; }
        
        /// <summary>
        /// <para>Valor da Base de cálculo do FCP.</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor da Base de cálculo do FCP.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vBCFCPST", Order=13)]
        public string vBCFCPST { get; set; }
        
        /// <summary>
        /// <para>Percentual de FCP retido por substituição tributária.</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros e 2 até 4 decimais. Utilizados em TAGs opcionais, não aceita valor zero.</para>
        /// <para xml:lang="en">Pattern: 0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Percentual de FCP retido por substituição tributária.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.Xml.Serialization.XmlElementAttribute("pFCPST", Order=14)]
        public string pFCPST { get; set; }
        
        /// <summary>
        /// <para>Valor do FCP retido por substituição tributária.</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor do FCP retido por substituição tributária.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vFCPST", Order=15)]
        public string vFCPST { get; set; }
        
        /// <summary>
        /// <para>Alíquota aplicável de cálculo do crédito (Simples Nacional). (v2.0)</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota aplicável de cálculo do crédito (Simples Nacional). (v2.0)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.Xml.Serialization.XmlElementAttribute("pCredSN", Order=16)]
        public string pCredSN { get; set; }
        
        /// <summary>
        /// <para>Valor crédito do ICMS que pode ser aproveitado nos termos do art. 23 da LC 123 (Simples Nacional) (v2.0)</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor crédito do ICMS que pode ser aproveitado nos termos do art. 23 da LC 123 (S" +
            "imples Nacional) (v2.0)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vCredICMSSN", Order=17)]
        public string vCredICMSSN { get; set; }
    }
}
