//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order "C:\Projetos.git\marco_teste\Novos XSD\PL_010b_NT2025_002_v1.30\nfe_v4.00.xsd"
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeIdeNFref", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeIdeNFref
    {
        
        /// <summary>
        /// <para>Chave de acesso das NF-e referenciadas. Chave de acesso compostas por Código da UF (tabela do IBGE) + AAMM da emissão + CNPJ do Emitente + modelo, série e número da NF-e Referenciada + Código Numérico + DV.</para>
        /// <para>Tipo Chave da Nota Fiscal Eletrônica</para>
        /// <para xml:lang="en">Maximum length: 44.</para>
        /// <para xml:lang="en">Pattern: [0-9]{44}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Chave de acesso das NF-e referenciadas. Chave de acesso compostas por Código da U" +
            "F (tabela do IBGE) + AAMM da emissão + CNPJ do Emitente + modelo, série e número" +
            " da NF-e Referenciada + Código Numérico + DV.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(44)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{44}")]
        [System.Xml.Serialization.XmlElementAttribute("refNFe", Order=0)]
        public string RefNFe { get; set; }
        
        /// <summary>
        /// <para>Referencia uma NF-e (modelo 55) emitida anteriormente pela sua Chave de Acesso com código numérico zerado, permitindo manter o sigilo da NF-e referenciada.</para>
        /// <para>Tipo Chave da Nota Fiscal Eletrônica</para>
        /// <para xml:lang="en">Maximum length: 44.</para>
        /// <para xml:lang="en">Pattern: [0-9]{44}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Referencia uma NF-e (modelo 55) emitida anteriormente pela sua Chave de Acesso co" +
            "m código numérico zerado, permitindo manter o sigilo da NF-e referenciada.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(44)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{44}")]
        [System.Xml.Serialization.XmlElementAttribute("refNFeSig", Order=1)]
        public string RefNFeSig { get; set; }
        
        /// <summary>
        /// <para>Dados da NF modelo 1/1A referenciada ou NF modelo 2 referenciada</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dados da NF modelo 1/1A referenciada ou NF modelo 2 referenciada")]
        [System.Xml.Serialization.XmlElementAttribute("refNF", Order=2)]
        public TNFeInfNFeIdeNFrefRefNF RefNF { get; set; }
        
        /// <summary>
        /// <para>Grupo com as informações NF de produtor referenciada</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo com as informações NF de produtor referenciada")]
        [System.Xml.Serialization.XmlElementAttribute("refNFP", Order=3)]
        public TNFeInfNFeIdeNFrefRefNFP RefNFP { get; set; }
        
        /// <summary>
        /// <para>Utilizar esta TAG para referenciar um CT-e emitido anteriormente, vinculada a NF-e atual</para>
        /// <para>Tipo Chave da Nota Fiscal Eletrônica</para>
        /// <para xml:lang="en">Maximum length: 44.</para>
        /// <para xml:lang="en">Pattern: [0-9]{44}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Utilizar esta TAG para referenciar um CT-e emitido anteriormente, vinculada a NF-" +
            "e atual")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(44)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{44}")]
        [System.Xml.Serialization.XmlElementAttribute("refCTe", Order=4)]
        public string RefCTe { get; set; }
        
        /// <summary>
        /// <para>Grupo do Cupom Fiscal vinculado à NF-e</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo do Cupom Fiscal vinculado à NF-e")]
        [System.Xml.Serialization.XmlElementAttribute("refECF", Order=5)]
        public TNFeInfNFeIdeNFrefRefECF RefECF { get; set; }
    }
}
