//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeDetImpostoCOFINSST", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeDetImpostoCOFINSST
    {
        
        /// <summary>
        /// <para>Valor da BC do COFINS ST</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor da BC do COFINS ST")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vBC", Order=0)]
        public string vBC { get; set; }
        
        /// <summary>
        /// <para>Alíquota do COFINS ST(em percentual)</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota do COFINS ST(em percentual)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.Xml.Serialization.XmlElementAttribute("pCOFINS", Order=1)]
        public string pCOFINS { get; set; }
        
        /// <summary>
        /// <para>Quantidade Vendida</para>
        /// <para>Tipo Decimal com 12 inteiros e 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{1,4}|[1-9]{1}[0-9]{0,11}|[1-9]{1}[0-9]{0,11}(\.[0-9]{4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Quantidade Vendida")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{1,4}|[1-9]{1}[0-9]{0,11}|[1-9]{1}[0-9]{0,11}(\\.[0-9]{4})?")]
        [System.Xml.Serialization.XmlElementAttribute("qBCProd", Order=2)]
        public string qBCProd { get; set; }
        
        /// <summary>
        /// <para>Alíquota do COFINS ST(em reais)</para>
        /// <para>Tipo Decimal com 11 inteiros, podendo ter 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{4}|[1-9]{1}[0-9]{0,10}(\.[0-9]{4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota do COFINS ST(em reais)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{4}|[1-9]{1}[0-9]{0,10}(\\.[0-9]{4})?")]
        [System.Xml.Serialization.XmlElementAttribute("vAliqProd", Order=3)]
        public string vAliqProd { get; set; }
        
        /// <summary>
        /// <para>Valor do COFINS ST</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor do COFINS ST")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vCOFINS", Order=4)]
        public string vCOFINS { get; set; }
        
        /// <summary>
        /// <para>Indica se o valor da COFINS ST compõe o valor total da NFe</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Indica se o valor da COFINS ST compõe o valor total da NFe")]
        [System.Xml.Serialization.XmlElementAttribute("indSomaCOFINSST", Order=5)]
        public TNFeInfNFeDetImpostoCOFINSSTIndSomaCOFINSST IndSomaCOFINSST { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IndSomaCOFINSST property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndSomaCOFINSSTSpecified { get; set; }
    }
}
