//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeDetImpostoICMSICMS15", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeDetImpostoICMSICMS15
    {
        
        /// <summary>
        /// <para>origem da mercadoria</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("origem da mercadoria")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("orig")]
        public Torig orig { get; set; }
        
        /// <summary>
        /// <para>Tributção pelo ICMS
        ///15= Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributção pelo ICMS 15= Tributação monofásica própria e com responsabilidade pela" +
            " retenção sobre combustíveis;")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CST")]
        public TNFeInfNFeDetImpostoICMSICMS15CST CST { get; set; }
        
        /// <summary>
        /// <para>Quantidade tributada.</para>
        /// <para>Tipo Decimal com 11 inteiros, podendo ter de 1 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{1,4}|[1-9]{1}[0-9]{0,10}|[1-9]{1}[0-9]{0,10}(\.[0-9]{1,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Quantidade tributada.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{1,4}|[1-9]{1}[0-9]{0,10}|[1-9]{1}[0-9]{0,10}(\\.[0-9]{1,4})?")]
        [System.Xml.Serialization.XmlElementAttribute("qBCMono")]
        public string QBCMono { get; set; }
        
        /// <summary>
        /// <para>Alíquota ad rem do imposto.</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota ad rem do imposto.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("adRemICMS")]
        public string AdRemICMS { get; set; }
        
        /// <summary>
        /// <para>Valor do ICMS próprio</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor do ICMS próprio")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vICMSMono")]
        public string VICMSMono { get; set; }
        
        /// <summary>
        /// <para>Quantidade tributada sujeita a retenção.</para>
        /// <para>Tipo Decimal com 11 inteiros, podendo ter de 1 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{1,4}|[1-9]{1}[0-9]{0,10}|[1-9]{1}[0-9]{0,10}(\.[0-9]{1,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Quantidade tributada sujeita a retenção.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{1,4}|[1-9]{1}[0-9]{0,10}|[1-9]{1}[0-9]{0,10}(\\.[0-9]{1,4})?")]
        [System.Xml.Serialization.XmlElementAttribute("qBCMonoReten")]
        public string QBCMonoReten { get; set; }
        
        /// <summary>
        /// <para>Alíquota ad rem do imposto com retenção.</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota ad rem do imposto com retenção.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("adRemICMSReten")]
        public string AdRemICMSReten { get; set; }
        
        /// <summary>
        /// <para>Valor do ICMS com retenção</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor do ICMS com retenção")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vICMSMonoReten")]
        public string VICMSMonoReten { get; set; }
        
        /// <summary>
        /// <para>Percentual de redução do valor da alíquota ad rem do ICMS.</para>
        /// <para>Tipo Decimal com 3 inteiros (no máximo 100), com 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0(\.[0-9]{2})?|100(\.00)?|[1-9]{1}[0-9]{0,1}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Percentual de redução do valor da alíquota ad rem do ICMS.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0(\\.[0-9]{2})?|100(\\.00)?|[1-9]{1}[0-9]{0,1}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("pRedAdRem")]
        public string PRedAdRem { get; set; }
        
        /// <summary>
        /// <para>Motivo da redução do adrem
        ///																							1= Transporte coletivo de passageiros; 9=Outros;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Motivo da redução do adrem 1= Transporte coletivo de passageiros; 9=Outros;")]
        [System.Xml.Serialization.XmlElementAttribute("motRedAdRem")]
        public TNFeInfNFeDetImpostoICMSICMS15MotRedAdRem MotRedAdRem { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MotRedAdRem property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MotRedAdRemSpecified { get; set; }
    }
}
