//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeDetProdDI", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeDetProdDI
    {
        
        /// <summary>
        /// <para>Número do Documento de Importação (DI, DSI, DIRE, DUImp) (NT2011/004)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do Documento de Importação (DI, DSI, DIRE, DUImp) (NT2011/004)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("nDI", Order=0)]
        public string nDI { get; set; }
        
        /// <summary>
        /// <para>Data de registro da DI/DSI/DA (AAAA-MM-DD)</para>
        /// <para>Tipo data AAAA-MM-DD</para>
        /// <para xml:lang="en">Pattern: (((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data de registro da DI/DSI/DA (AAAA-MM-DD)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-" +
            "((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29" +
            "|30)))))")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dDI", Order=1)]
        public string dDI { get; set; }
        
        /// <summary>
        /// <para>Local do desembaraço aduaneiro</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Local do desembaraço aduaneiro")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xLocDesemb", Order=2)]
        public string xLocDesemb { get; set; }
        
        /// <summary>
        /// <para>UF onde ocorreu o desembaraço aduaneiro</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("UF onde ocorreu o desembaraço aduaneiro")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("UFDesemb", Order=3)]
        public IWTNFCompleto.BibliotecaDatasets.v4_0.TUfEmi UFDesemb { get; set; }
        
        /// <summary>
        /// <para>Data do desembaraço aduaneiro (AAAA-MM-DD)</para>
        /// <para>Tipo data AAAA-MM-DD</para>
        /// <para xml:lang="en">Pattern: (((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data do desembaraço aduaneiro (AAAA-MM-DD)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-" +
            "((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29" +
            "|30)))))")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dDesemb", Order=4)]
        public string dDesemb { get; set; }
        
        /// <summary>
        /// <para>Via de transporte internacional informada na DI ou na Declaração Única de Importação (DUImp):
        ///																	1-Maritima;2-Fluvial;3-Lacustre;4-Aerea;5-Postal;6-Ferroviaria;7-Rodoviaria;8-Conduto;9-Meios Proprios;10-Entrada/Saida Ficta;
        ///																	11-Courier;12-Em maos;13-Por reboque.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Via de transporte internacional informada na DI ou na Declaração Única de Importação (DUImp): 1-Maritima;2-Fluvial;3-Lacustre;4-Aerea;5-Postal;6-Ferroviaria;7-Rodoviaria;8-Conduto;9-Meios Proprios;10-Entrada/Saida Ficta; 11-Courier;12-Em maos;13-Por reboque.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpViaTransp", Order=5)]
        public TNFeInfNFeDetProdDITpViaTransp tpViaTransp { get; set; }
        
        /// <summary>
        /// <para>Valor Adicional ao frete para renovação de marinha mercante</para>
        /// <para>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor Adicional ao frete para renovação de marinha mercante")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vAFRMM", Order=6)]
        public string vAFRMM { get; set; }
        
        /// <summary>
        /// <para>Forma de Importação quanto a intermediação 
        ///																	1-por conta propria;2-por conta e ordem;3-encomenda</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Forma de Importação quanto a intermediação 1-por conta propria;2-por conta e orde" +
            "m;3-encomenda")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpIntermedio", Order=7)]
        public TNFeInfNFeDetProdDITpIntermedio tpIntermedio { get; set; }
        
        /// <summary>
        /// <para>CNPJ do adquirente ou do encomendante</para>
        /// <para>Tipo Número do CNPJ</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CNPJ do adquirente ou do encomendante")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.Xml.Serialization.XmlElementAttribute("CNPJ", Order=8)]
        public string CNPJ { get; set; }
        
        /// <summary>
        /// <para>CPF do adquirente ou do encomendante</para>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CPF do adquirente ou do encomendante")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.Xml.Serialization.XmlElementAttribute("CPF", Order=9)]
        public string CPF { get; set; }
        
        /// <summary>
        /// <para>Sigla da UF do adquirente ou do encomendante</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Sigla da UF do adquirente ou do encomendante")]
        [System.Xml.Serialization.XmlElementAttribute("UFTerceiro", Order=10)]
        public IWTNFCompleto.BibliotecaDatasets.v4_0.TUfEmi UFTerceiro { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the UFTerceiro property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UFTerceiroSpecified { get; set; }
        
        /// <summary>
        /// <para>Código do exportador (usado nos sistemas internos de informação do emitente da NF-e)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código do exportador (usado nos sistemas internos de informação do emitente da NF" +
            "-e)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("cExportador", Order=11)]
        public string cExportador { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TNFeInfNFeDetProdDIAdi> _adi;
        
        /// <summary>
        /// <para>Adições (NT 2011/004)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Adições (NT 2011/004)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("adi", Order=12)]
        public System.Collections.ObjectModel.Collection<TNFeInfNFeDetProdDIAdi> adi
        {
            get
            {
                return _adi;
            }
            set
            {
                _adi = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TNFeInfNFeDetProdDI" /> class.</para>
        /// </summary>
        public TNFeInfNFeDetProdDI()
        {
            this._adi = new System.Collections.ObjectModel.Collection<TNFeInfNFeDetProdDIAdi>();
        }
    }
}
