//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order "C:\Projetos.git\marco_teste\Novos XSD\PL_010b_NT2025_002_v1.30\nfe_v4.00.xsd"
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeDetImpostoPISPISOutrCST", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    public enum TNFeInfNFeDetImpostoPISPISOutrCST
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("49")]
        Item49,
        
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        
        [System.Xml.Serialization.XmlEnumAttribute("51")]
        Item51,
        
        [System.Xml.Serialization.XmlEnumAttribute("52")]
        Item52,
        
        [System.Xml.Serialization.XmlEnumAttribute("53")]
        Item53,
        
        [System.Xml.Serialization.XmlEnumAttribute("54")]
        Item54,
        
        [System.Xml.Serialization.XmlEnumAttribute("55")]
        Item55,
        
        [System.Xml.Serialization.XmlEnumAttribute("56")]
        Item56,
        
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
        
        [System.Xml.Serialization.XmlEnumAttribute("61")]
        Item61,
        
        [System.Xml.Serialization.XmlEnumAttribute("62")]
        Item62,
        
        [System.Xml.Serialization.XmlEnumAttribute("63")]
        Item63,
        
        [System.Xml.Serialization.XmlEnumAttribute("64")]
        Item64,
        
        [System.Xml.Serialization.XmlEnumAttribute("65")]
        Item65,
        
        [System.Xml.Serialization.XmlEnumAttribute("66")]
        Item66,
        
        [System.Xml.Serialization.XmlEnumAttribute("67")]
        Item67,
        
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        
        [System.Xml.Serialization.XmlEnumAttribute("71")]
        Item71,
        
        [System.Xml.Serialization.XmlEnumAttribute("72")]
        Item72,
        
        [System.Xml.Serialization.XmlEnumAttribute("73")]
        Item73,
        
        [System.Xml.Serialization.XmlEnumAttribute("74")]
        Item74,
        
        [System.Xml.Serialization.XmlEnumAttribute("75")]
        Item75,
        
        [System.Xml.Serialization.XmlEnumAttribute("98")]
        Item98,
        
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
}
