//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeDet", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeDet
    {
        
        /// <summary>
        /// <para>Dados dos produtos e serviços da NF-e</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dados dos produtos e serviços da NF-e")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("prod", Order=0)]
        public TNFeInfNFeDetProd prod { get; set; }
        
        /// <summary>
        /// <para>Tributos incidentes nos produtos ou serviços da NF-e</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributos incidentes nos produtos ou serviços da NF-e")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("imposto", Order=1)]
        public TNFeInfNFeDetImposto imposto { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("impostoDevol", Order=2)]
        public TNFeInfNFeDetImpostoDevol impostoDevol { get; set; }
        
        /// <summary>
        /// <para>Informações adicionais do produto (norma referenciada, informações complementares, etc)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 500.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informações adicionais do produto (norma referenciada, informações complementares" +
            ", etc)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(500)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("infAdProd", Order=3)]
        public string infAdProd { get; set; }
        
        /// <summary>
        /// <para>Grupo de observações de uso livre (para o item da NF-e)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de observações de uso livre (para o item da NF-e)")]
        [System.Xml.Serialization.XmlElementAttribute("obsItem", Order=4)]
        public TNFeInfNFeDetObsItem ObsItem { get; set; }
        
        /// <summary>
        /// <para>Número do item do NF</para>
        /// <para xml:lang="en">Pattern: [1-9]{1}[0-9]{0,1}|[1-8]{1}[0-9]{2}|[9]{1}[0-8]{1}[0-9]{1}|[9]{1}[9]{1}[0]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do item do NF")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]{1}[0-9]{0,1}|[1-8]{1}[0-9]{2}|[9]{1}[0-8]{1}[0-9]{1}|[9]{1}[9]{1}[0]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("nItem")]
        public string nItem { get; set; }
    }
}
