//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeDest", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeDest
    {
        
        /// <summary>
        /// <para>Número do CNPJ</para>
        /// <para>Tipo Número do CNPJ</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do CNPJ")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.Xml.Serialization.XmlElementAttribute("CNPJ")]
        public string CNPJ { get; set; }
        
        /// <summary>
        /// <para>Número do CPF</para>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do CPF")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.Xml.Serialization.XmlElementAttribute("CPF")]
        public string CPF { get; set; }
        
        /// <summary>
        /// <para>Identificador do destinatário, em caso de comprador estrangeiro</para>
        /// <para xml:lang="en">Pattern: ([!-ÿ]{0}|[!-ÿ]{5,20})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identificador do destinatário, em caso de comprador estrangeiro")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([!-ÿ]{0}|[!-ÿ]{5,20})?")]
        [System.Xml.Serialization.XmlElementAttribute("idEstrangeiro")]
        public string IdEstrangeiro { get; set; }
        
        /// <summary>
        /// <para>Razão Social ou nome do destinatário</para>
        /// <para xml:lang="en">Minimum length: 2.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Razão Social ou nome do destinatário")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("xNome")]
        public string xNome { get; set; }
        
        /// <summary>
        /// <para>Dados do endereço</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dados do endereço")]
        [System.Xml.Serialization.XmlElementAttribute("enderDest")]
        public TEndereco enderDest { get; set; }
        
        /// <summary>
        /// <para>Indicador da IE do destinatário:
        ///1 – Contribuinte ICMSpagamento à vista;
        ///2 – Contribuinte isento de inscrição;
        ///9 – Não Contribuinte</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Indicador da IE do destinatário: 1 – Contribuinte ICMSpagamento à vista; 2 – Cont" +
            "ribuinte isento de inscrição; 9 – Não Contribuinte")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("indIEDest")]
        public TNFeInfNFeDestIndIEDest indIEDest { get; set; }
        
        /// <summary>
        /// <para>Inscrição Estadual (obrigatório nas operações com contribuintes do ICMS)</para>
        /// <para>Tipo Inscrição Estadual do Destinatário // alterado para aceitar vazio ou ISENTO - maio/2010 v2.0</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{2,14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Inscrição Estadual (obrigatório nas operações com contribuintes do ICMS)")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{2,14}")]
        [System.Xml.Serialization.XmlElementAttribute("IE")]
        public string IE { get; set; }
        
        /// <summary>
        /// <para>Inscrição na SUFRAMA (Obrigatório nas operações com as áreas com benefícios de incentivos fiscais sob controle da SUFRAMA) PL_005d - 11/08/09 - alterado para aceitar 8 ou 9 dígitos</para>
        /// <para xml:lang="en">Pattern: [0-9]{8,9}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Inscrição na SUFRAMA (Obrigatório nas operações com as áreas com benefícios de in" +
            "centivos fiscais sob controle da SUFRAMA) PL_005d - 11/08/09 - alterado para ace" +
            "itar 8 ou 9 dígitos")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{8,9}")]
        [System.Xml.Serialization.XmlElementAttribute("ISUF")]
        public string ISUF { get; set; }
        
        /// <summary>
        /// <para>Inscrição Municipal do tomador do serviço</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Inscrição Municipal do tomador do serviço")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("IM")]
        public string IM { get; set; }
        
        /// <summary>
        /// <para>Informar o e-mail do destinatário. O campo pode ser utilizado para informar o e-mail
        ///de recepção da NF-e indicada pelo destinatário</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informar o e-mail do destinatário. O campo pode ser utilizado para informar o e-m" +
            "ail de recepção da NF-e indicada pelo destinatário")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.Xml.Serialization.XmlElementAttribute("email")]
        public string email { get; set; }
    }
}
