//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order "C:\Projetos.git\marco_teste\Novos XSD\PL_010b_NT2025_002_v1.30\nfe_v4.00.xsd"
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    /// <summary>
    /// <para>Tipo Nota Fiscal Eletrônica</para>
    /// <para>Nota Fiscal Eletrônica</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo Nota Fiscal Eletrônica Nota Fiscal Eletrônica")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFe", Namespace="http://www.portalfiscal.inf.br/nfe")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("NFe", Namespace="http://www.portalfiscal.inf.br/nfe")]
    public partial class TNFe
    {
        
        /// <summary>
        /// <para>Informações da Nota Fiscal eletrônica</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informações da Nota Fiscal eletrônica")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("infNFe", Order=0)]
        public TNFeInfNFe infNFe { get; set; }
        
        /// <summary>
        /// <para>Informações suplementares Nota Fiscal</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informações suplementares Nota Fiscal")]
        [System.Xml.Serialization.XmlElementAttribute("infNFeSupl", Order=1)]
        public TNFeInfNFeSupl infNFeSupl { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Signature", Order=2, Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public IWTNFCompleto.BibliotecaDatasets.v4_0.SignatureType Signature { get; set; }
    }
}
