//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retEnviNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNFeInfNFeDetImpostoICMS", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNFeInfNFeDetImpostoICMS
    {
        
        /// <summary>
        /// <para>Tributação pelo ICMS
        ///00 - Tributada integralmente</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação pelo ICMS 00 - Tributada integralmente")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS00")]
        public TNFeInfNFeDetImpostoICMSICMS00 ICMS00 { get; set; }
        
        /// <summary>
        /// <para>Tributação monofásica própria sobre combustíveis</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação monofásica própria sobre combustíveis")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS02")]
        public TNFeInfNFeDetImpostoICMSICMS02 ICMS02 { get; set; }
        
        /// <summary>
        /// <para>Tributação pelo ICMS
        ///10 - Tributada e com cobrança do ICMS por substituição tributária</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação pelo ICMS 10 - Tributada e com cobrança do ICMS por substituição tribu" +
            "tária")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS10")]
        public TNFeInfNFeDetImpostoICMSICMS10 ICMS10 { get; set; }
        
        /// <summary>
        /// <para>Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação monofásica própria e com responsabilidade pela retenção sobre combustí" +
            "veis")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS15")]
        public TNFeInfNFeDetImpostoICMSICMS15 ICMS15 { get; set; }
        
        /// <summary>
        /// <para>Tributção pelo ICMS
        ///20 - Com redução de base de cálculo</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributção pelo ICMS 20 - Com redução de base de cálculo")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS20")]
        public TNFeInfNFeDetImpostoICMSICMS20 ICMS20 { get; set; }
        
        /// <summary>
        /// <para>Tributação pelo ICMS
        ///30 - Isenta ou não tributada e com cobrança do ICMS por substituição tributária</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação pelo ICMS 30 - Isenta ou não tributada e com cobrança do ICMS por subs" +
            "tituição tributária")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS30")]
        public TNFeInfNFeDetImpostoICMSICMS30 ICMS30 { get; set; }
        
        /// <summary>
        /// <para>Tributação pelo ICMS
        ///40 - Isenta 
        ///41 - Não tributada 
        ///50 - Suspensão</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação pelo ICMS 40 - Isenta 41 - Não tributada 50 - Suspensão")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS40")]
        public TNFeInfNFeDetImpostoICMSICMS40 ICMS40 { get; set; }
        
        /// <summary>
        /// <para>Tributção pelo ICMS 51 - Diferimento. A exigência do preenchimento das informações do ICMS diferido fica à critério de cada UF.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributção pelo ICMS 51 - Diferimento. A exigência do preenchimento das informaçõe" +
            "s do ICMS diferido fica à critério de cada UF.")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS51")]
        public TNFeInfNFeDetImpostoICMSICMS51 ICMS51 { get; set; }
        
        /// <summary>
        /// <para>Tributação monofásica sobre combustíveis com recolhimento diferido</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação monofásica sobre combustíveis com recolhimento diferido")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS53")]
        public TNFeInfNFeDetImpostoICMSICMS53 ICMS53 { get; set; }
        
        /// <summary>
        /// <para>Tributação pelo ICMS
        ///60 - ICMS cobrado anteriormente por substituição tributária</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação pelo ICMS 60 - ICMS cobrado anteriormente por substituição tributária")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS60")]
        public TNFeInfNFeDetImpostoICMSICMS60 ICMS60 { get; set; }
        
        /// <summary>
        /// <para>Tributação monofásica sobre combustíveis cobrada anteriormente;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação monofásica sobre combustíveis cobrada anteriormente;")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS61")]
        public TNFeInfNFeDetImpostoICMSICMS61 ICMS61 { get; set; }
        
        /// <summary>
        /// <para>Tributação pelo ICMS 
        ///70 - Com redução de base de cálculo e cobrança do ICMS por substituição tributária</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação pelo ICMS 70 - Com redução de base de cálculo e cobrança do ICMS por s" +
            "ubstituição tributária")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS70")]
        public TNFeInfNFeDetImpostoICMSICMS70 ICMS70 { get; set; }
        
        /// <summary>
        /// <para>Tributação pelo ICMS
        ///90 - Outras</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação pelo ICMS 90 - Outras")]
        [System.Xml.Serialization.XmlElementAttribute("ICMS90")]
        public TNFeInfNFeDetImpostoICMSICMS90 ICMS90 { get; set; }
        
        /// <summary>
        /// <para>Partilha do ICMS entre a UF de origem e UF de destino ou a UF definida na legislação
        ///Operação interestadual para consumidor final com partilha do ICMS  devido na operação entre a UF de origem e a UF do destinatário ou ou a UF definida na legislação. (Ex. UF da concessionária de entrega do  veículos)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Partilha do ICMS entre a UF de origem e UF de destino ou a UF definida na legislação Operação interestadual para consumidor final com partilha do ICMS devido na operação entre a UF de origem e a UF do destinatário ou ou a UF definida na legislação. (Ex. UF da concessionária de entrega do veículos)")]
        [System.Xml.Serialization.XmlElementAttribute("ICMSPart")]
        public TNFeInfNFeDetImpostoICMSICMSPart ICMSPart { get; set; }
        
        /// <summary>
        /// <para>Grupo de informação do ICMSST devido para a UF de destino, nas operações interestaduais de produtos que tiveram retenção antecipada de ICMS por ST na UF do remetente. Repasse via Substituto Tributário.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informação do ICMSST devido para a UF de destino, nas operações interest" +
            "aduais de produtos que tiveram retenção antecipada de ICMS por ST na UF do remet" +
            "ente. Repasse via Substituto Tributário.")]
        [System.Xml.Serialization.XmlElementAttribute("ICMSST")]
        public TNFeInfNFeDetImpostoICMSICMSST ICMSST { get; set; }
        
        /// <summary>
        /// <para>Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=101 (v.2.0)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=101 (v.2.0)")]
        [System.Xml.Serialization.XmlElementAttribute("ICMSSN101")]
        public TNFeInfNFeDetImpostoICMSICMSSN101 ICMSSN101 { get; set; }
        
        /// <summary>
        /// <para>Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=102, 103, 300 ou 400 (v.2.0))</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=102, 103, 300 ou 400 (v.2.0))")]
        [System.Xml.Serialization.XmlElementAttribute("ICMSSN102")]
        public TNFeInfNFeDetImpostoICMSICMSSN102 ICMSSN102 { get; set; }
        
        /// <summary>
        /// <para>Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=201 (v.2.0)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=201 (v.2.0)")]
        [System.Xml.Serialization.XmlElementAttribute("ICMSSN201")]
        public TNFeInfNFeDetImpostoICMSICMSSN201 ICMSSN201 { get; set; }
        
        /// <summary>
        /// <para>Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=202 ou 203 (v.2.0)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=202 ou 203 (v.2.0)")]
        [System.Xml.Serialization.XmlElementAttribute("ICMSSN202")]
        public TNFeInfNFeDetImpostoICMSICMSSN202 ICMSSN202 { get; set; }
        
        /// <summary>
        /// <para>Tributação do ICMS pelo SIMPLES NACIONAL,CRT=1 – Simples Nacional e CSOSN=500 (v.2.0)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação do ICMS pelo SIMPLES NACIONAL,CRT=1 – Simples Nacional e CSOSN=500 (v." +
            "2.0)")]
        [System.Xml.Serialization.XmlElementAttribute("ICMSSN500")]
        public TNFeInfNFeDetImpostoICMSICMSSN500 ICMSSN500 { get; set; }
        
        /// <summary>
        /// <para>Tributação do ICMS pelo SIMPLES NACIONAL, CRT=1 – Simples Nacional, CRT=4 - MEI e CSOSN=900 (v2.0)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tributação do ICMS pelo SIMPLES NACIONAL, CRT=1 – Simples Nacional, CRT=4 - MEI e" +
            " CSOSN=900 (v2.0)")]
        [System.Xml.Serialization.XmlElementAttribute("ICMSSN900")]
        public TNFeInfNFeDetImpostoICMSICMSSN900 ICMSSN900 { get; set; }
    }
}
