//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order "C:\Projetos.git\marco_teste\Novos XSD\PL_010b_NT2025_002_v1.30\nfe_v4.00.xsd"
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    /// <summary>
    /// <para>Tipo Redução Base de Cálculo</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo Redução Base de Cálculo")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TRed", Namespace="http://www.portalfiscal.inf.br/nfe")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TRed
    {
        
        /// <summary>
        /// <para>Percentual de redução de aliquota do cClassTrib</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Percentual de redução de aliquota do cClassTrib")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("pRedAliq", Order=0)]
        public string PRedAliq { get; set; }
        
        /// <summary>
        /// <para>Aliquota Efetiva que será aplicada a Base de Calculo (em percentual)</para>
        /// <para>Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Aliquota Efetiva que será aplicada a Base de Calculo (em percentual)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2,4})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("pAliqEfet", Order=1)]
        public string PAliqEfet { get; set; }
    }
}
