//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map C:\Temp\PL_009\retConsSitNFe_v4.00.xsd
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TRetCancNFeInfCanc", Namespace="http://www.portalfiscal.inf.br/nfe", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TRetCancNFeInfCanc
    {
        
        /// <summary>
        /// <para>Identificação do Ambiente:
        ///1 - Produção
        ///2 - Homologação</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identificação do Ambiente: 1 - Produção 2 - Homologação")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpAmb")]
        public IWTNFCompleto.BibliotecaDatasets.v4_0.TAmb tpAmb { get; set; }
        
        /// <summary>
        /// <para>Versão do Aplicativo que processou o pedido de cancelamento</para>
        /// <para>Tipo Versão do Aplicativo</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Versão do Aplicativo que processou o pedido de cancelamento")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("verAplic")]
        public string verAplic { get; set; }
        
        /// <summary>
        /// <para>Código do status da mensagem enviada.</para>
        /// <para>Tipo Código da Mensagem enviada</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [0-9]{3}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código do status da mensagem enviada.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{3}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cStat")]
        public string cStat { get; set; }
        
        /// <summary>
        /// <para>Descrição literal do status do serviço solicitado.</para>
        /// <para>Tipo Motivo</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição literal do status do serviço solicitado.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xMotivo")]
        public string xMotivo { get; set; }
        
        /// <summary>
        /// <para>código da UF de atendimento</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("código da UF de atendimento")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cUF")]
        public IWTNFCompleto.BibliotecaDatasets.v4_0.TCodUfIBGE cUF { get; set; }
        
        /// <summary>
        /// <para>Chaves de acesso da NF-e, compostas por: UF do emitente, AAMM da emissão da NFe, CNPJ do emitente, modelo, série e número da NF-e e código numérico + DV.</para>
        /// <para>Tipo Chave da Nota Fiscal Eletrônica</para>
        /// <para xml:lang="en">Maximum length: 44.</para>
        /// <para xml:lang="en">Pattern: [0-9]{44}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Chaves de acesso da NF-e, compostas por: UF do emitente, AAMM da emissão da NFe, " +
            "CNPJ do emitente, modelo, série e número da NF-e e código numérico + DV.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(44)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{44}")]
        [System.Xml.Serialization.XmlElementAttribute("chNFe")]
        public string chNFe { get; set; }
        
        /// <summary>
        /// <para>Data e hora de recebimento, no formato AAAA-MM-DDTHH:MM:SS. Deve ser preenchida com data e hora da gravação no Banco em caso de Confirmação.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data e hora de recebimento, no formato AAAA-MM-DDTHH:MM:SS. Deve ser preenchida c" +
            "om data e hora da gravação no Banco em caso de Confirmação.")]
        [System.Xml.Serialization.XmlElementAttribute("dhRecbto", DataType="dateTime")]
        public System.DateTime dhRecbto { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the dhRecbto property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dhRecbtoSpecified { get; set; }
        
        /// <summary>
        /// <para>Número do Protocolo de Status da NF-e. 1 posição (1 – Secretaria de Fazenda Estadual 2 – Receita Federal); 2 - código da UF - 2 posições ano; 10 seqüencial no ano.</para>
        /// <para>Tipo Número do Protocolo de Status</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [0-9]{15}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do Protocolo de Status da NF-e. 1 posição (1 – Secretaria de Fazenda Estad" +
            "ual 2 – Receita Federal); 2 - código da UF - 2 posições ano; 10 seqüencial no an" +
            "o.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{15}")]
        [System.Xml.Serialization.XmlElementAttribute("nProt")]
        public string nProt { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
    }
}
