//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// XmlSchemaClassGenerator.Console -v --output C:\Projetos.git\Recursos.C#.IWTNfeCompleto\BibliotecasDatasets\novo --namespace IWTNFCompleto.BibliotecaDatasets.v4_0 --separateFiles --collectionSettersMode Public --namingScheme Legacy --typeNameSubstituteFile C:\Projetos.git\Recursos.C#.IWTNfeCompleto\correcoes.map --order "C:\Projetos.git\marco_teste\Novos XSD\PL_010b_NT2025_002_v1.30\nfe_v4.00.xsd"
namespace IWTNFCompleto.BibliotecaDatasets.v4_0
{
    
    
    /// <summary>
    /// <para>Grupo de informações da Tributação da NFe</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Grupo de informações da Tributação da NFe")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TTribNFe", Namespace="http://www.portalfiscal.inf.br/nfe")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TTribNFe
    {
        
        /// <summary>
        /// <para>Código Situação Tributária do IBS/CBS</para>
        /// <para>Código Situação Tributária do IBS/CBS</para>
        /// <para xml:lang="en">Pattern: \d{3}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código Situação Tributária do IBS/CBS")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{3}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CST", Order=0)]
        public string CST { get; set; }
        
        /// <summary>
        /// <para>Código de Classificação Tributária do IBS e da CBS</para>
        /// <para xml:lang="en">Pattern: \d{6}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{6}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cClassTrib", Order=1)]
        public string CClassTrib { get; set; }
        
        /// <summary>
        /// <para>Indica se a operação é de doação</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Indica se a operação é de doação")]
        [System.Xml.Serialization.XmlElementAttribute("indDoacao", Order=2)]
        public TIndDoacao IndDoacao { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IndDoacao property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndDoacaoSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gIBSCBS", Order=3)]
        public TCIBS GIBSCBS { get; set; }
        
        /// <summary>
        /// <para>Informar essa opção da Choice para Monofasia (CST 620)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informar essa opção da Choice para Monofasia (CST 620)")]
        [System.Xml.Serialization.XmlElementAttribute("gIBSCBSMono", Order=4)]
        public TMonofasia GIBSCBSMono { get; set; }
        
        /// <summary>
        /// <para>Informar essa opção da Choice para o CST 800</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informar essa opção da Choice para o CST 800")]
        [System.Xml.Serialization.XmlElementAttribute("gTransfCred", Order=5)]
        public TTransfCred GTransfCred { get; set; }
        
        /// <summary>
        /// <para>Informar essa opção da Choice para o CST 811</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informar essa opção da Choice para o CST 811")]
        [System.Xml.Serialization.XmlElementAttribute("gAjusteCompet", Order=6)]
        public TAjusteCompet GAjusteCompet { get; set; }
        
        /// <summary>
        /// <para>Informado conforme indicador no cClassTrib</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informado conforme indicador no cClassTrib")]
        [System.Xml.Serialization.XmlElementAttribute("gEstornoCred", Order=7)]
        public TEstornoCred GEstornoCred { get; set; }
        
        /// <summary>
        /// <para>Crédito Presumido da Operação. Informado conforme indicador no cClassTrib.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Crédito Presumido da Operação. Informado conforme indicador no cClassTrib.")]
        [System.Xml.Serialization.XmlElementAttribute("gCredPresOper", Order=8)]
        public TCredPresOper GCredPresOper { get; set; }
        
        /// <summary>
        /// <para>Classificação de acordo com o art. 450, § 1º, da LC 214/25 para o cálculo do crédito presumido na ZFM. Informado conforme indicador no cClassTrib.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Classificação de acordo com o art. 450, § 1º, da LC 214/25 para o cálculo do créd" +
            "ito presumido na ZFM. Informado conforme indicador no cClassTrib.")]
        [System.Xml.Serialization.XmlElementAttribute("gCredPresIBSZFM", Order=9)]
        public TCredPresIBSZFM GCredPresIBSZFM { get; set; }
    }
}
